# Publish a build for release.
name: KMMBridge-Release
on:
  workflow_dispatch:

jobs:
  call-publish:
    uses: ./.github/workflows/Base-Publish.yml
    permissions:
      contents: write
      packages: write
    with:
      build-debug: false
